spring:
  application:
    name: allra-backend-assignment

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/allra
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql : trace
      SQL: debug
